---
 - hosts: api-env
   gather_facts: false
   tasks:
      - name: download Microsoft repository GPG keys
        shell: "wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb"

      - name: Register the Microsoft repository GPG keys
        become: yes
        shell: "dpkg -i /tmp/packages-microsoft-prod.deb"

      - name: update repository and install dependencies
        become: yes
        shell: |
          add-apt-repository universe
          apt update
          apt install apt-transport-https
          apt update
          apt install dotnet-sdk-3.1 -y
        
